from io import BytesIO

from lawu.cf import ClassFile
from lawu.attributes.source_file import SourceFileAttribute
from lawu.constants import UTF8


def test_sourcefile_read(loader):
    """
    Ensure we can read a SourceFileAttribute generated by javac.
    """
    cf = loader['HelloWorldDebug']
    source_file = cf.attributes.find_one(name='SourceFile')
    assert(source_file.source_file.value == 'HelloWorldDebug.java')


def test_sourcefile_write():
    """
    Ensure SourceFileAttribute can be written and read back.
    """
    cf_one = ClassFile(this='SourceFileTest')

    with cf_one:
        sfa = cf_one.attributes.create(SourceFileAttribute)
        sfa.source_file = UTF8(value='SourceFileTest.java')

    fout = BytesIO()
    cf_one.save(fout)

    fin = BytesIO(fout.getvalue())
    cf_two = ClassFile(fin)

    source_file = cf_two.attributes.find_one(name='SourceFile')
    assert(source_file.source_file.value == 'SourceFileTest.java')
