from jawa.cf import ClassFile
from jawa.attributes.source_file import SourceFileAttribute
from jawa.constants import UTF8


def test_sourcefile_read(loader):
    """
    Ensure we can read a SourceFileAttribute generated by javac.
    """
    cf = loader['HelloWorldDebug']
    source_file = cf.attributes.find_one(name='SourceFile')
    assert(source_file.source_file.value == 'HelloWorldDebug.java')


def test_sourcefile_write():
    """
    Ensure SourceFileAttribute can be written and read back.
    """
    cf_one = ClassFile.create('SourceFileTest')
    sfa = cf_one.attributes.create(SourceFileAttribute)
    sfa.source_file = UTF8(pool=cf_one.constants, value='SourceFileTest.java')
    assert sfa.pack() == b'\x00\x06'
