from jawa.cf import ClassFile
from jawa.attributes.deprecated import DeprecatedAttribute


def test_deprecated_read(loader):
    """
    Ensure we can read a DeprecatedAttribute generated by javac.
    """
    cf = loader['Deprecated']
    assert cf.attributes.find_one(name='Deprecated') is not None


def test_deprecated_write():
    """
    Ensure DeprecatedAttribute can be written and read back.
    """
    cf_one = ClassFile.create('Comparable')
    dep = cf_one.attributes.create(DeprecatedAttribute)
    assert dep.pack() == b''
