from jawa.cf import ClassFile
from jawa.constants import Integer
from jawa.attributes.constant_value import ConstantValueAttribute


def test_constant_value_read(loader):
    """
    Ensure we can read a ConstantValue generated by javac.
    """
    cf = loader['ConstantValue']
    field = cf.fields.find_one(name='CONSTANT')
    const = field.attributes.find_one(name='ConstantValue')
    assert const.value.value == 1


def test_constant_value_create():
    """
    Ensure ConstantValue shortcuts work.
    """
    cf = ClassFile.create('ConstantValue')

    field = cf.fields.create('CONSTANT', 'I', value=Integer(
        pool=cf.constants,
        value=1
    ))

    const = field.attributes.find_one(name='ConstantValue')
    assert const.value.value == 1


def test_constant_value_write():
    """
    Ensure we can write ConstantValue.
    """
    cf = ClassFile.create('ConstantValue')
    const = cf.attributes.create(ConstantValueAttribute)
    const.value = Integer(pool=cf.constants, value=1)
    assert const.pack() == b'\x00\x06'
