from jawa.cf import ClassFile
from jawa.attributes.signature import SignatureAttribute
from jawa.constants import UTF8


def test_signature_read(loader):
    """
    Ensure we can read a SignatureAttribute generated by javac.
    """
    cf = loader['Comparable']
    sig = cf.attributes.find_one(name='Signature')
    assert sig.signature.value == \
        '<T:Ljava/lang/Object;>Ljava/lang/Object;'


def test_signature_write():
    """
    Ensure SignatureAttribute can be written and read back.
    """
    cf_one = ClassFile.create('Comparable')
    sig = cf_one.attributes.create(SignatureAttribute)
    sig.signature = UTF8(
        pool=cf_one.constants,
        value='<T:Ljava/lang/Object;>Ljava/lang/Object;'
    )
    assert sig.pack() == b'\x00\x06'
